package com.dingli.comment.bean;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class BusinessExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table business
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table business
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table business
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public BusinessExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table business
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andImgFileNameIsNull() {
            addCriterion("img_file_name is null");
            return (Criteria) this;
        }

        public Criteria andImgFileNameIsNotNull() {
            addCriterion("img_file_name is not null");
            return (Criteria) this;
        }

        public Criteria andImgFileNameEqualTo(String value) {
            addCriterion("img_file_name =", value, "imgFileName");
            return (Criteria) this;
        }

        public Criteria andImgFileNameNotEqualTo(String value) {
            addCriterion("img_file_name <>", value, "imgFileName");
            return (Criteria) this;
        }

        public Criteria andImgFileNameGreaterThan(String value) {
            addCriterion("img_file_name >", value, "imgFileName");
            return (Criteria) this;
        }

        public Criteria andImgFileNameGreaterThanOrEqualTo(String value) {
            addCriterion("img_file_name >=", value, "imgFileName");
            return (Criteria) this;
        }

        public Criteria andImgFileNameLessThan(String value) {
            addCriterion("img_file_name <", value, "imgFileName");
            return (Criteria) this;
        }

        public Criteria andImgFileNameLessThanOrEqualTo(String value) {
            addCriterion("img_file_name <=", value, "imgFileName");
            return (Criteria) this;
        }

        public Criteria andImgFileNameLike(String value) {
            addCriterion("img_file_name like", value, "imgFileName");
            return (Criteria) this;
        }

        public Criteria andImgFileNameNotLike(String value) {
            addCriterion("img_file_name not like", value, "imgFileName");
            return (Criteria) this;
        }

        public Criteria andImgFileNameIn(List<String> values) {
            addCriterion("img_file_name in", values, "imgFileName");
            return (Criteria) this;
        }

        public Criteria andImgFileNameNotIn(List<String> values) {
            addCriterion("img_file_name not in", values, "imgFileName");
            return (Criteria) this;
        }

        public Criteria andImgFileNameBetween(String value1, String value2) {
            addCriterion("img_file_name between", value1, value2, "imgFileName");
            return (Criteria) this;
        }

        public Criteria andImgFileNameNotBetween(String value1, String value2) {
            addCriterion("img_file_name not between", value1, value2, "imgFileName");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andSubtitleIsNull() {
            addCriterion("subtitle is null");
            return (Criteria) this;
        }

        public Criteria andSubtitleIsNotNull() {
            addCriterion("subtitle is not null");
            return (Criteria) this;
        }

        public Criteria andSubtitleEqualTo(String value) {
            addCriterion("subtitle =", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleNotEqualTo(String value) {
            addCriterion("subtitle <>", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleGreaterThan(String value) {
            addCriterion("subtitle >", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleGreaterThanOrEqualTo(String value) {
            addCriterion("subtitle >=", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleLessThan(String value) {
            addCriterion("subtitle <", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleLessThanOrEqualTo(String value) {
            addCriterion("subtitle <=", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleLike(String value) {
            addCriterion("subtitle like", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleNotLike(String value) {
            addCriterion("subtitle not like", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleIn(List<String> values) {
            addCriterion("subtitle in", values, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleNotIn(List<String> values) {
            addCriterion("subtitle not in", values, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleBetween(String value1, String value2) {
            addCriterion("subtitle between", value1, value2, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleNotBetween(String value1, String value2) {
            addCriterion("subtitle not between", value1, value2, "subtitle");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(BigDecimal value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(BigDecimal value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(BigDecimal value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(BigDecimal value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<BigDecimal> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<BigDecimal> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andDistanceIsNull() {
            addCriterion("distance is null");
            return (Criteria) this;
        }

        public Criteria andDistanceIsNotNull() {
            addCriterion("distance is not null");
            return (Criteria) this;
        }

        public Criteria andDistanceEqualTo(Integer value) {
            addCriterion("distance =", value, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceNotEqualTo(Integer value) {
            addCriterion("distance <>", value, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceGreaterThan(Integer value) {
            addCriterion("distance >", value, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceGreaterThanOrEqualTo(Integer value) {
            addCriterion("distance >=", value, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceLessThan(Integer value) {
            addCriterion("distance <", value, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceLessThanOrEqualTo(Integer value) {
            addCriterion("distance <=", value, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceIn(List<Integer> values) {
            addCriterion("distance in", values, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceNotIn(List<Integer> values) {
            addCriterion("distance not in", values, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceBetween(Integer value1, Integer value2) {
            addCriterion("distance between", value1, value2, "distance");
            return (Criteria) this;
        }

        public Criteria andDistanceNotBetween(Integer value1, Integer value2) {
            addCriterion("distance not between", value1, value2, "distance");
            return (Criteria) this;
        }

        public Criteria andNumberIsNull() {
            addCriterion("number is null");
            return (Criteria) this;
        }

        public Criteria andNumberIsNotNull() {
            addCriterion("number is not null");
            return (Criteria) this;
        }

        public Criteria andNumberEqualTo(Integer value) {
            addCriterion("number =", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotEqualTo(Integer value) {
            addCriterion("number <>", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberGreaterThan(Integer value) {
            addCriterion("number >", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("number >=", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberLessThan(Integer value) {
            addCriterion("number <", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberLessThanOrEqualTo(Integer value) {
            addCriterion("number <=", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberIn(List<Integer> values) {
            addCriterion("number in", values, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotIn(List<Integer> values) {
            addCriterion("number not in", values, "number");
            return (Criteria) this;
        }

        public Criteria andNumberBetween(Integer value1, Integer value2) {
            addCriterion("number between", value1, value2, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("number not between", value1, value2, "number");
            return (Criteria) this;
        }

        public Criteria andDescsIsNull() {
            addCriterion("descs is null");
            return (Criteria) this;
        }

        public Criteria andDescsIsNotNull() {
            addCriterion("descs is not null");
            return (Criteria) this;
        }

        public Criteria andDescsEqualTo(String value) {
            addCriterion("descs =", value, "descs");
            return (Criteria) this;
        }

        public Criteria andDescsNotEqualTo(String value) {
            addCriterion("descs <>", value, "descs");
            return (Criteria) this;
        }

        public Criteria andDescsGreaterThan(String value) {
            addCriterion("descs >", value, "descs");
            return (Criteria) this;
        }

        public Criteria andDescsGreaterThanOrEqualTo(String value) {
            addCriterion("descs >=", value, "descs");
            return (Criteria) this;
        }

        public Criteria andDescsLessThan(String value) {
            addCriterion("descs <", value, "descs");
            return (Criteria) this;
        }

        public Criteria andDescsLessThanOrEqualTo(String value) {
            addCriterion("descs <=", value, "descs");
            return (Criteria) this;
        }

        public Criteria andDescsLike(String value) {
            addCriterion("descs like", value, "descs");
            return (Criteria) this;
        }

        public Criteria andDescsNotLike(String value) {
            addCriterion("descs not like", value, "descs");
            return (Criteria) this;
        }

        public Criteria andDescsIn(List<String> values) {
            addCriterion("descs in", values, "descs");
            return (Criteria) this;
        }

        public Criteria andDescsNotIn(List<String> values) {
            addCriterion("descs not in", values, "descs");
            return (Criteria) this;
        }

        public Criteria andDescsBetween(String value1, String value2) {
            addCriterion("descs between", value1, value2, "descs");
            return (Criteria) this;
        }

        public Criteria andDescsNotBetween(String value1, String value2) {
            addCriterion("descs not between", value1, value2, "descs");
            return (Criteria) this;
        }

        public Criteria andCitysIsNull() {
            addCriterion("citys is null");
            return (Criteria) this;
        }

        public Criteria andCitysIsNotNull() {
            addCriterion("citys is not null");
            return (Criteria) this;
        }

        public Criteria andCitysEqualTo(String value) {
            addCriterion("citys =", value, "citys");
            return (Criteria) this;
        }

        public Criteria andCitysNotEqualTo(String value) {
            addCriterion("citys <>", value, "citys");
            return (Criteria) this;
        }

        public Criteria andCitysGreaterThan(String value) {
            addCriterion("citys >", value, "citys");
            return (Criteria) this;
        }

        public Criteria andCitysGreaterThanOrEqualTo(String value) {
            addCriterion("citys >=", value, "citys");
            return (Criteria) this;
        }

        public Criteria andCitysLessThan(String value) {
            addCriterion("citys <", value, "citys");
            return (Criteria) this;
        }

        public Criteria andCitysLessThanOrEqualTo(String value) {
            addCriterion("citys <=", value, "citys");
            return (Criteria) this;
        }

        public Criteria andCitysLike(String value) {
            addCriterion("citys like", value, "citys");
            return (Criteria) this;
        }

        public Criteria andCitysNotLike(String value) {
            addCriterion("citys not like", value, "citys");
            return (Criteria) this;
        }

        public Criteria andCitysIn(List<String> values) {
            addCriterion("citys in", values, "citys");
            return (Criteria) this;
        }

        public Criteria andCitysNotIn(List<String> values) {
            addCriterion("citys not in", values, "citys");
            return (Criteria) this;
        }

        public Criteria andCitysBetween(String value1, String value2) {
            addCriterion("citys between", value1, value2, "citys");
            return (Criteria) this;
        }

        public Criteria andCitysNotBetween(String value1, String value2) {
            addCriterion("citys not between", value1, value2, "citys");
            return (Criteria) this;
        }

        public Criteria andCategorysIsNull() {
            addCriterion("categorys is null");
            return (Criteria) this;
        }

        public Criteria andCategorysIsNotNull() {
            addCriterion("categorys is not null");
            return (Criteria) this;
        }

        public Criteria andCategorysEqualTo(String value) {
            addCriterion("categorys =", value, "categorys");
            return (Criteria) this;
        }

        public Criteria andCategorysNotEqualTo(String value) {
            addCriterion("categorys <>", value, "categorys");
            return (Criteria) this;
        }

        public Criteria andCategorysGreaterThan(String value) {
            addCriterion("categorys >", value, "categorys");
            return (Criteria) this;
        }

        public Criteria andCategorysGreaterThanOrEqualTo(String value) {
            addCriterion("categorys >=", value, "categorys");
            return (Criteria) this;
        }

        public Criteria andCategorysLessThan(String value) {
            addCriterion("categorys <", value, "categorys");
            return (Criteria) this;
        }

        public Criteria andCategorysLessThanOrEqualTo(String value) {
            addCriterion("categorys <=", value, "categorys");
            return (Criteria) this;
        }

        public Criteria andCategorysLike(String value) {
            addCriterion("categorys like", value, "categorys");
            return (Criteria) this;
        }

        public Criteria andCategorysNotLike(String value) {
            addCriterion("categorys not like", value, "categorys");
            return (Criteria) this;
        }

        public Criteria andCategorysIn(List<String> values) {
            addCriterion("categorys in", values, "categorys");
            return (Criteria) this;
        }

        public Criteria andCategorysNotIn(List<String> values) {
            addCriterion("categorys not in", values, "categorys");
            return (Criteria) this;
        }

        public Criteria andCategorysBetween(String value1, String value2) {
            addCriterion("categorys between", value1, value2, "categorys");
            return (Criteria) this;
        }

        public Criteria andCategorysNotBetween(String value1, String value2) {
            addCriterion("categorys not between", value1, value2, "categorys");
            return (Criteria) this;
        }

        public Criteria andStarTotalNumsIsNull() {
            addCriterion("star_total_nums is null");
            return (Criteria) this;
        }

        public Criteria andStarTotalNumsIsNotNull() {
            addCriterion("star_total_nums is not null");
            return (Criteria) this;
        }

        public Criteria andStarTotalNumsEqualTo(Integer value) {
            addCriterion("star_total_nums =", value, "starTotalNums");
            return (Criteria) this;
        }

        public Criteria andStarTotalNumsNotEqualTo(Integer value) {
            addCriterion("star_total_nums <>", value, "starTotalNums");
            return (Criteria) this;
        }

        public Criteria andStarTotalNumsGreaterThan(Integer value) {
            addCriterion("star_total_nums >", value, "starTotalNums");
            return (Criteria) this;
        }

        public Criteria andStarTotalNumsGreaterThanOrEqualTo(Integer value) {
            addCriterion("star_total_nums >=", value, "starTotalNums");
            return (Criteria) this;
        }

        public Criteria andStarTotalNumsLessThan(Integer value) {
            addCriterion("star_total_nums <", value, "starTotalNums");
            return (Criteria) this;
        }

        public Criteria andStarTotalNumsLessThanOrEqualTo(Integer value) {
            addCriterion("star_total_nums <=", value, "starTotalNums");
            return (Criteria) this;
        }

        public Criteria andStarTotalNumsIn(List<Integer> values) {
            addCriterion("star_total_nums in", values, "starTotalNums");
            return (Criteria) this;
        }

        public Criteria andStarTotalNumsNotIn(List<Integer> values) {
            addCriterion("star_total_nums not in", values, "starTotalNums");
            return (Criteria) this;
        }

        public Criteria andStarTotalNumsBetween(Integer value1, Integer value2) {
            addCriterion("star_total_nums between", value1, value2, "starTotalNums");
            return (Criteria) this;
        }

        public Criteria andStarTotalNumsNotBetween(Integer value1, Integer value2) {
            addCriterion("star_total_nums not between", value1, value2, "starTotalNums");
            return (Criteria) this;
        }

        public Criteria andCommentTotalNumsIsNull() {
            addCriterion("comment_total_nums is null");
            return (Criteria) this;
        }

        public Criteria andCommentTotalNumsIsNotNull() {
            addCriterion("comment_total_nums is not null");
            return (Criteria) this;
        }

        public Criteria andCommentTotalNumsEqualTo(Integer value) {
            addCriterion("comment_total_nums =", value, "commentTotalNums");
            return (Criteria) this;
        }

        public Criteria andCommentTotalNumsNotEqualTo(Integer value) {
            addCriterion("comment_total_nums <>", value, "commentTotalNums");
            return (Criteria) this;
        }

        public Criteria andCommentTotalNumsGreaterThan(Integer value) {
            addCriterion("comment_total_nums >", value, "commentTotalNums");
            return (Criteria) this;
        }

        public Criteria andCommentTotalNumsGreaterThanOrEqualTo(Integer value) {
            addCriterion("comment_total_nums >=", value, "commentTotalNums");
            return (Criteria) this;
        }

        public Criteria andCommentTotalNumsLessThan(Integer value) {
            addCriterion("comment_total_nums <", value, "commentTotalNums");
            return (Criteria) this;
        }

        public Criteria andCommentTotalNumsLessThanOrEqualTo(Integer value) {
            addCriterion("comment_total_nums <=", value, "commentTotalNums");
            return (Criteria) this;
        }

        public Criteria andCommentTotalNumsIn(List<Integer> values) {
            addCriterion("comment_total_nums in", values, "commentTotalNums");
            return (Criteria) this;
        }

        public Criteria andCommentTotalNumsNotIn(List<Integer> values) {
            addCriterion("comment_total_nums not in", values, "commentTotalNums");
            return (Criteria) this;
        }

        public Criteria andCommentTotalNumsBetween(Integer value1, Integer value2) {
            addCriterion("comment_total_nums between", value1, value2, "commentTotalNums");
            return (Criteria) this;
        }

        public Criteria andCommentTotalNumsNotBetween(Integer value1, Integer value2) {
            addCriterion("comment_total_nums not between", value1, value2, "commentTotalNums");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table business
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 20 15:09:12 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table business
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}