package com.dingli.comment.bean;

import java.math.BigDecimal;

public class Business {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.id
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.img_file_name
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    private String imgFileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.title
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.subtitle
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    private String subtitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.price
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.distance
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    private Integer distance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.number
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.descs
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    private String descs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.citys
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    private String citys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.categorys
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    private String categorys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.star_total_nums
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    private Integer starTotalNums;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.comment_total_nums
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    private Integer commentTotalNums;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.id
     *
     * @return the value of business.id
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.id
     *
     * @param id the value for business.id
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.img_file_name
     *
     * @return the value of business.img_file_name
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public String getImgFileName() {
        return imgFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.img_file_name
     *
     * @param imgFileName the value for business.img_file_name
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public void setImgFileName(String imgFileName) {
        this.imgFileName = imgFileName == null ? null : imgFileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.title
     *
     * @return the value of business.title
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.title
     *
     * @param title the value for business.title
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.subtitle
     *
     * @return the value of business.subtitle
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.subtitle
     *
     * @param subtitle the value for business.subtitle
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle == null ? null : subtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.price
     *
     * @return the value of business.price
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.price
     *
     * @param price the value for business.price
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.distance
     *
     * @return the value of business.distance
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public Integer getDistance() {
        return distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.distance
     *
     * @param distance the value for business.distance
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public void setDistance(Integer distance) {
        this.distance = distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.number
     *
     * @return the value of business.number
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.number
     *
     * @param number the value for business.number
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.descs
     *
     * @return the value of business.descs
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public String getDescs() {
        return descs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.descs
     *
     * @param descs the value for business.descs
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public void setDescs(String descs) {
        this.descs = descs == null ? null : descs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.citys
     *
     * @return the value of business.citys
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public String getCitys() {
        return citys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.citys
     *
     * @param citys the value for business.citys
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public void setCitys(String citys) {
        this.citys = citys == null ? null : citys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.categorys
     *
     * @return the value of business.categorys
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public String getCategorys() {
        return categorys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.categorys
     *
     * @param categorys the value for business.categorys
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public void setCategorys(String categorys) {
        this.categorys = categorys == null ? null : categorys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.star_total_nums
     *
     * @return the value of business.star_total_nums
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public Integer getStarTotalNums() {
        return starTotalNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.star_total_nums
     *
     * @param starTotalNums the value for business.star_total_nums
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public void setStarTotalNums(Integer starTotalNums) {
        this.starTotalNums = starTotalNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.comment_total_nums
     *
     * @return the value of business.comment_total_nums
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public Integer getCommentTotalNums() {
        return commentTotalNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.comment_total_nums
     *
     * @param commentTotalNums the value for business.comment_total_nums
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public void setCommentTotalNums(Integer commentTotalNums) {
        this.commentTotalNums = commentTotalNums;
    }
}