package com.dingli.comment.bean;

public class Sys_group_action {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group_action.id
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group_action.group_id
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group_action.action_id
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    private Integer actionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group_action.id
     *
     * @return the value of sys_group_action.id
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group_action.id
     *
     * @param id the value for sys_group_action.id
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group_action.group_id
     *
     * @return the value of sys_group_action.group_id
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group_action.group_id
     *
     * @param groupId the value for sys_group_action.group_id
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group_action.action_id
     *
     * @return the value of sys_group_action.action_id
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public Integer getActionId() {
        return actionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group_action.action_id
     *
     * @param actionId the value for sys_group_action.action_id
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    public void setActionId(Integer actionId) {
        this.actionId = actionId;
    }
}