package com.dingli.comment.dao;

import com.dingli.comment.bean.Dic;
import com.dingli.comment.bean.DicExample;
import com.dingli.comment.bean.DicKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    int countByExample(DicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    int deleteByExample(DicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    int deleteByPrimaryKey(DicKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    int insert(Dic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    int insertSelective(Dic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    List<Dic> selectByExample(DicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    Dic selectByPrimaryKey(DicKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    int updateByExampleSelective(@Param("record") Dic record, @Param("example") DicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    int updateByExample(@Param("record") Dic record, @Param("example") DicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    int updateByPrimaryKeySelective(Dic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    int updateByPrimaryKey(Dic record);
}