package com.dingli.comment.dao;

import com.dingli.comment.bean.Sys_group_action;
import com.dingli.comment.bean.Sys_group_actionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Sys_group_actionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group_action
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    int countByExample(Sys_group_actionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group_action
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    int deleteByExample(Sys_group_actionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group_action
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group_action
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    int insert(Sys_group_action record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group_action
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    int insertSelective(Sys_group_action record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group_action
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    List<Sys_group_action> selectByExample(Sys_group_actionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group_action
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    Sys_group_action selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group_action
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    int updateByExampleSelective(@Param("record") Sys_group_action record, @Param("example") Sys_group_actionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group_action
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    int updateByExample(@Param("record") Sys_group_action record, @Param("example") Sys_group_actionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group_action
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    int updateByPrimaryKeySelective(Sys_group_action record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_group_action
     *
     * @mbggenerated Mon Aug 20 15:09:12 CST 2018
     */
    int updateByPrimaryKey(Sys_group_action record);
}